<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="common_properties.xacro"/>
    <xacro:property name="base_length" value="0.5"/>
    <xacro:property name="base_width" value="0.52"/>
    <xacro:property name="base_height" value="0.05"/>
    <xacro:property name="wheel_radius" value="0.055"/>
    <xacro:property name="wheel_length" value="0.052"/>
    <xacro:property name="caster_radius" value="${wheel_radius / 2.0}"/>



    <!-- <frame name="lidar_frame" attached_to='laser_frame'>
        <pose>0 0 0 0 0 0</pose>
    </frame> -->



    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
         xyz="0 0 ${2*base_height / 2.0}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </collision>
    </link>
    <!-- <gazebo reference="base_link">
        <material>Gazebo/White</material>
    </gazebo> -->
    <link name="custom_model">
    <visual>
        <geometry>
            <mesh filename="file://$(find pal_robot)/config/redlinear_v.dae"/>
        </geometry>
        <origin xyz="0 0 0.1" rpy="0 0 1.57"/>
        <!-- <material name="Gazebo/White"/> -->
    </visual>
    <xacro:box_inertia m="5.0" l="0.5" w="0.5" h="0.1"
         xyz="0 0 0.25" rpy="0 0 0" />
    <collision>
        <geometry>
            <mesh filename="file://$(find pal_robot)/config/redlinear_v.dae"/>
        </geometry>
        <origin xyz="0 0 0.1" rpy="0 0 1.57"/>
    </collision>
</link>

<joint name="base_to_custom_model" type="fixed">
    <parent link="base_link"/>
    <child link="custom_model"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
</joint>

    <link name="imu">
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <material name="white"/>
        </visual>
        <xacro:box_inertia m="1.0" l="0.1" w="0.1" h="0.1"
         xyz="0 0 0.05" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="imu">
        <material>Gazebo/Red</material>
    </gazebo>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
                <material name ="grey"/>
            </visual>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            </collision>
        </link>
    </xacro:macro>
    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="0.05" h="0.04" xyz="0 0 0" rpy="0 0 0"/>
    </link>
    <link name="laser_base">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.08"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.08"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="0.05" h="0.08" xyz="0 0 0" rpy="0 0 0"/>
    </link>
    <gazebo reference="laser_base">
        <material>Gazebo/White</material>
    </gazebo>
    <!-- <gazebo reference="laser_frame">
  <sensor type="ray" name="lidar_front_sensor">
        <pose>0 0 0 0 0 0</pose>
        <always_on>true</always_on>
        <visualize>true</visualize>
        <update_rate>10</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1</resolution>
              <min_angle>-3.14159</min_angle>
              <max_angle>3.14159</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.5</min>
            <max>30</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.01</stddev>
        </noise>
        </ray>   
        <plugin name="lidar_front_ray_sensor_plugin" filename="libgazebo_ros_ray_sensor.so">
          <ros>
            <namespace>/lidar</namespace>
            <remapping>~/out:=/scan</remapping> 
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
          <frame_name>laser_frame</frame_name>
        </plugin>
  </sensor>
</gazebo> -->

    <xacro:wheel_link prefix="left"/>
    <xacro:wheel_link prefix="right"/>
    
    
    <gazebo reference="left_wheel_link">
        <material>Gazebo/Black</material>
        <mu1 value="1500"/>
        <mu2 value="1500"/>
    </gazebo>
    <gazebo reference="right_wheel_link">
        <material>Gazebo/Black</material>
        <mu1 value="1500"/>
        <mu2 value="1500"/>
    </gazebo>
    

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <xacro:sphere_inertia m="0.5" r="${2*caster_radius}" xyz="0 0 0" rpy="0 0 0" />
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
    </link>
    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Black</material>
        <mu1 value="0.01"/>
        <mu2 value="0.01"/>
    </gazebo>
    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${-((base_width / 2.0) + (wheel_length/2.0))} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit velocity="100" effort="100"/>
    </joint>
    <joint name="laser_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_base"/>
        <origin xyz="0.0 0.0 0.05" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
        <limit velocity="100" effort="100"/>
    </joint>
    <joint name="laser_joint" type="fixed">
        <parent link="laser_base"/>
        <child link="laser_frame"/>
        <origin xyz="0.0 0.0 0.04" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
        <limit velocity="100" effort="100"/>
    </joint>
    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu"/>
        <origin xyz="0.0 0.0 0.05" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
        <limit velocity="100" effort="100"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${(base_width / 2.0) + (wheel_length/2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit velocity="100" effort="100"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length / 3.0} 0 ${-caster_radius}" rpy="0 0 0"/>
    </joint>
</robot>
